@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsaWJyYXJ5Iiwic3ViIjoieXVzdWZAZ21haWx6LmNvbSIsImFwcF91c2VyX2lkIjoyLCJhdXRob3JpdGllcyI6WyJBZG1pbiJdLCJleHAiOjE3MzQ0NDI1MjB9.CotV22ehqM3OcSj5enVrr-uERQG2TGdlXK_fyjY42vk
GET http://localhost:8080/api/books/1 HTTP/1.1

###
GET http://localhost:8080/api/books HTTP/1.1

###
GET http://localhost:8080/api/books/title/Chemistry HTTP/1.1

###
GET http://localhost:8080/api/books/author/Conteh HTTP/1.1

###
GET http://localhost:8080/api/books/genre/Science HTTP/1.1

###
POST http://localhost:8080/api/books HTTP/1.1
Content-Type: application/json

{
    "author": "yusuf"
}

###
DELETE http://localhost:8080/api/books/3 HTTP/1.1


###
POST http://localhost:8080/api/books HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "title": "Conceptual",
    "author": "Koidia",
    "genre": "Science",
    "copiesAvailable": 5
}

###
PUT http://localhost:8080/api/books/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "id": 1,
    "title": "Cemistry",
    "author": "Conteh",
    "genre": "Science",
    "copiesAvailable": 4
}