GET http://localhost:8080/api/users/1 HTTP/1.1

###
GET http://localhost:8080/api/users HTTP/1.1

###
GET http://localhost:8080/api/users/email/yusuf@gmail.com HTTP/1.1

###
POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
    "email": "yusuf@gma.com",
    "firstName": "Yusuf",
    "lastName": "Jaiteh",
    "password": "dkkgj",
    "role": "Admin"
}

###
DELETE http://localhost:8080/api/users/3 HTTP/1.1

###
PUT http://localhost:8080/api/users/3 HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "email": "yusuf@gmaill.com",
    "firstName": "Yusuf",
    "lastName": "Jaiteh",
    "password": "dkkgj",
    "role": "Admin"
}